/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedQuarterlyRouteImport } from './routes/_authenticated/quarterly'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMidyearRouteImport } from './routes/_authenticated/midyear'
import { Route as AuthenticatedEndyearRouteImport } from './routes/_authenticated/endyear'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAppraisalRouteImport } from './routes/_authenticated/appraisal'
import { Route as AuthenticatedAppealsRouteImport } from './routes/_authenticated/appeals'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicPayrollSyncRouteImport } from './routes/api/public/payroll-sync'
import { Route as ApiPublicBootstrapSuper26RouteImport } from './routes/api/public/bootstrap-super26'
import { Route as AuthenticatedSupervisorInboxRouteImport } from './routes/_authenticated/supervisor.inbox'
import { Route as AuthenticatedCommitteeAppealsRouteImport } from './routes/_authenticated/committee.appeals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin.sync'
import { Route as AuthenticatedAdminStatusRouteImport } from './routes/_authenticated/admin.status'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminOrgStructureRouteImport } from './routes/_authenticated/admin.org-structure'
import { Route as AuthenticatedAdminLoginAuditRouteImport } from './routes/_authenticated/admin.login-audit'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminCyclesRouteImport } from './routes/_authenticated/admin.cycles'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedSupervisorReviewIdRouteImport } from './routes/_authenticated/supervisor.review.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuarterlyRoute = AuthenticatedQuarterlyRouteImport.update({
  id: '/quarterly',
  path: '/quarterly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMidyearRoute = AuthenticatedMidyearRouteImport.update({
  id: '/midyear',
  path: '/midyear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEndyearRoute = AuthenticatedEndyearRouteImport.update({
  id: '/endyear',
  path: '/endyear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalRoute = AuthenticatedAppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsRoute = AuthenticatedAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPayrollSyncRoute = ApiPublicPayrollSyncRouteImport.update({
  id: '/api/public/payroll-sync',
  path: '/api/public/payroll-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapSuper26Route =
  ApiPublicBootstrapSuper26RouteImport.update({
    id: '/api/public/bootstrap-super26',
    path: '/api/public/bootstrap-super26',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSupervisorInboxRoute =
  AuthenticatedSupervisorInboxRouteImport.update({
    id: '/supervisor/inbox',
    path: '/supervisor/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommitteeAppealsRoute =
  AuthenticatedCommitteeAppealsRouteImport.update({
    id: '/committee/appeals',
    path: '/committee/appeals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/admin/sync',
  path: '/admin/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStatusRoute =
  AuthenticatedAdminStatusRouteImport.update({
    id: '/admin/status',
    path: '/admin/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrgStructureRoute =
  AuthenticatedAdminOrgStructureRouteImport.update({
    id: '/admin/org-structure',
    path: '/admin/org-structure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoginAuditRoute =
  AuthenticatedAdminLoginAuditRouteImport.update({
    id: '/admin/login-audit',
    path: '/admin/login-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCyclesRoute =
  AuthenticatedAdminCyclesRouteImport.update({
    id: '/admin/cycles',
    path: '/admin/cycles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/admin/contracts',
    path: '/admin/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorReviewIdRoute =
  AuthenticatedSupervisorReviewIdRouteImport.update({
    id: '/supervisor/review/$id',
    path: '/supervisor/review/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/endyear': typeof AuthenticatedEndyearRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quarterly': typeof AuthenticatedQuarterlyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/status': typeof AuthenticatedAdminStatusRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/endyear': typeof AuthenticatedEndyearRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quarterly': typeof AuthenticatedQuarterlyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/status': typeof AuthenticatedAdminStatusRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/appeals': typeof AuthenticatedAppealsRoute
  '/_authenticated/appraisal': typeof AuthenticatedAppraisalRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/endyear': typeof AuthenticatedEndyearRoute
  '/_authenticated/midyear': typeof AuthenticatedMidyearRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quarterly': typeof AuthenticatedQuarterlyRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/_authenticated/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/status': typeof AuthenticatedAdminStatusRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/_authenticated/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appeals'
    | '/appraisal'
    | '/change-password'
    | '/dashboard'
    | '/endyear'
    | '/midyear'
    | '/profile'
    | '/quarterly'
    | '/search'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/cycles'
    | '/admin/import'
    | '/admin/login-audit'
    | '/admin/org-structure'
    | '/admin/roles'
    | '/admin/status'
    | '/admin/sync'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/admin/'
    | '/supervisor/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appeals'
    | '/appraisal'
    | '/change-password'
    | '/dashboard'
    | '/endyear'
    | '/midyear'
    | '/profile'
    | '/quarterly'
    | '/search'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/cycles'
    | '/admin/import'
    | '/admin/login-audit'
    | '/admin/org-structure'
    | '/admin/roles'
    | '/admin/status'
    | '/admin/sync'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/admin'
    | '/supervisor/review/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/appeals'
    | '/_authenticated/appraisal'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/endyear'
    | '/_authenticated/midyear'
    | '/_authenticated/profile'
    | '/_authenticated/quarterly'
    | '/_authenticated/search'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/cycles'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/login-audit'
    | '/_authenticated/admin/org-structure'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/status'
    | '/_authenticated/admin/sync'
    | '/_authenticated/admin/users'
    | '/_authenticated/committee/appeals'
    | '/_authenticated/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/_authenticated/admin/'
    | '/_authenticated/supervisor/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicBootstrapSuper26Route: typeof ApiPublicBootstrapSuper26Route
  ApiPublicPayrollSyncRoute: typeof ApiPublicPayrollSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quarterly': {
      id: '/_authenticated/quarterly'
      path: '/quarterly'
      fullPath: '/quarterly'
      preLoaderRoute: typeof AuthenticatedQuarterlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/midyear': {
      id: '/_authenticated/midyear'
      path: '/midyear'
      fullPath: '/midyear'
      preLoaderRoute: typeof AuthenticatedMidyearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/endyear': {
      id: '/_authenticated/endyear'
      path: '/endyear'
      fullPath: '/endyear'
      preLoaderRoute: typeof AuthenticatedEndyearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisal': {
      id: '/_authenticated/appraisal'
      path: '/appraisal'
      fullPath: '/appraisal'
      preLoaderRoute: typeof AuthenticatedAppraisalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals': {
      id: '/_authenticated/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AuthenticatedAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payroll-sync': {
      id: '/api/public/payroll-sync'
      path: '/api/public/payroll-sync'
      fullPath: '/api/public/payroll-sync'
      preLoaderRoute: typeof ApiPublicPayrollSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-super26': {
      id: '/api/public/bootstrap-super26'
      path: '/api/public/bootstrap-super26'
      fullPath: '/api/public/bootstrap-super26'
      preLoaderRoute: typeof ApiPublicBootstrapSuper26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supervisor/inbox': {
      id: '/_authenticated/supervisor/inbox'
      path: '/supervisor/inbox'
      fullPath: '/supervisor/inbox'
      preLoaderRoute: typeof AuthenticatedSupervisorInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee/appeals': {
      id: '/_authenticated/committee/appeals'
      path: '/committee/appeals'
      fullPath: '/committee/appeals'
      preLoaderRoute: typeof AuthenticatedCommitteeAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/admin/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/status': {
      id: '/_authenticated/admin/status'
      path: '/admin/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AuthenticatedAdminStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/org-structure': {
      id: '/_authenticated/admin/org-structure'
      path: '/admin/org-structure'
      fullPath: '/admin/org-structure'
      preLoaderRoute: typeof AuthenticatedAdminOrgStructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/login-audit': {
      id: '/_authenticated/admin/login-audit'
      path: '/admin/login-audit'
      fullPath: '/admin/login-audit'
      preLoaderRoute: typeof AuthenticatedAdminLoginAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cycles': {
      id: '/_authenticated/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AuthenticatedAdminCyclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/review/$id': {
      id: '/_authenticated/supervisor/review/$id'
      path: '/supervisor/review/$id'
      fullPath: '/supervisor/review/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppealsRoute: typeof AuthenticatedAppealsRoute
  AuthenticatedAppraisalRoute: typeof AuthenticatedAppraisalRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEndyearRoute: typeof AuthenticatedEndyearRoute
  AuthenticatedMidyearRoute: typeof AuthenticatedMidyearRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuarterlyRoute: typeof AuthenticatedQuarterlyRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminCyclesRoute: typeof AuthenticatedAdminCyclesRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLoginAuditRoute: typeof AuthenticatedAdminLoginAuditRoute
  AuthenticatedAdminOrgStructureRoute: typeof AuthenticatedAdminOrgStructureRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminStatusRoute: typeof AuthenticatedAdminStatusRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCommitteeAppealsRoute: typeof AuthenticatedCommitteeAppealsRoute
  AuthenticatedSupervisorInboxRoute: typeof AuthenticatedSupervisorInboxRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSupervisorReviewIdRoute: typeof AuthenticatedSupervisorReviewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppealsRoute: AuthenticatedAppealsRoute,
  AuthenticatedAppraisalRoute: AuthenticatedAppraisalRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEndyearRoute: AuthenticatedEndyearRoute,
  AuthenticatedMidyearRoute: AuthenticatedMidyearRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuarterlyRoute: AuthenticatedQuarterlyRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminCyclesRoute: AuthenticatedAdminCyclesRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLoginAuditRoute: AuthenticatedAdminLoginAuditRoute,
  AuthenticatedAdminOrgStructureRoute: AuthenticatedAdminOrgStructureRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminStatusRoute: AuthenticatedAdminStatusRoute,
  AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCommitteeAppealsRoute: AuthenticatedCommitteeAppealsRoute,
  AuthenticatedSupervisorInboxRoute: AuthenticatedSupervisorInboxRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSupervisorReviewIdRoute: AuthenticatedSupervisorReviewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicBootstrapSuper26Route: ApiPublicBootstrapSuper26Route,
  ApiPublicPayrollSyncRoute: ApiPublicPayrollSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
