/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMidyearRouteImport } from './routes/_authenticated/midyear'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppraisalRouteImport } from './routes/_authenticated/appraisal'
import { Route as AuthenticatedAppealsRouteImport } from './routes/_authenticated/appeals'
import { Route as AuthenticatedSupervisorInboxRouteImport } from './routes/_authenticated/supervisor.inbox'
import { Route as AuthenticatedCommitteeAppealsRouteImport } from './routes/_authenticated/committee.appeals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedSupervisorReviewIdRouteImport } from './routes/_authenticated/supervisor.review.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMidyearRoute = AuthenticatedMidyearRouteImport.update({
  id: '/midyear',
  path: '/midyear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppraisalRoute = AuthenticatedAppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsRoute = AuthenticatedAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorInboxRoute =
  AuthenticatedSupervisorInboxRouteImport.update({
    id: '/supervisor/inbox',
    path: '/supervisor/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommitteeAppealsRoute =
  AuthenticatedCommitteeAppealsRouteImport.update({
    id: '/committee/appeals',
    path: '/committee/appeals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorReviewIdRoute =
  AuthenticatedSupervisorReviewIdRouteImport.update({
    id: '/supervisor/review/$id',
    path: '/supervisor/review/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appeals': typeof AuthenticatedAppealsRoute
  '/_authenticated/appraisal': typeof AuthenticatedAppraisalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/midyear': typeof AuthenticatedMidyearRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/_authenticated/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/_authenticated/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appeals'
    | '/appraisal'
    | '/dashboard'
    | '/midyear'
    | '/admin/roles'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/supervisor/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appeals'
    | '/appraisal'
    | '/dashboard'
    | '/midyear'
    | '/admin/roles'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/supervisor/review/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appeals'
    | '/_authenticated/appraisal'
    | '/_authenticated/dashboard'
    | '/_authenticated/midyear'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/committee/appeals'
    | '/_authenticated/supervisor/inbox'
    | '/_authenticated/supervisor/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/midyear': {
      id: '/_authenticated/midyear'
      path: '/midyear'
      fullPath: '/midyear'
      preLoaderRoute: typeof AuthenticatedMidyearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisal': {
      id: '/_authenticated/appraisal'
      path: '/appraisal'
      fullPath: '/appraisal'
      preLoaderRoute: typeof AuthenticatedAppraisalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals': {
      id: '/_authenticated/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AuthenticatedAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/inbox': {
      id: '/_authenticated/supervisor/inbox'
      path: '/supervisor/inbox'
      fullPath: '/supervisor/inbox'
      preLoaderRoute: typeof AuthenticatedSupervisorInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee/appeals': {
      id: '/_authenticated/committee/appeals'
      path: '/committee/appeals'
      fullPath: '/committee/appeals'
      preLoaderRoute: typeof AuthenticatedCommitteeAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/review/$id': {
      id: '/_authenticated/supervisor/review/$id'
      path: '/supervisor/review/$id'
      fullPath: '/supervisor/review/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppealsRoute: typeof AuthenticatedAppealsRoute
  AuthenticatedAppraisalRoute: typeof AuthenticatedAppraisalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMidyearRoute: typeof AuthenticatedMidyearRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCommitteeAppealsRoute: typeof AuthenticatedCommitteeAppealsRoute
  AuthenticatedSupervisorInboxRoute: typeof AuthenticatedSupervisorInboxRoute
  AuthenticatedSupervisorReviewIdRoute: typeof AuthenticatedSupervisorReviewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppealsRoute: AuthenticatedAppealsRoute,
  AuthenticatedAppraisalRoute: AuthenticatedAppraisalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMidyearRoute: AuthenticatedMidyearRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCommitteeAppealsRoute: AuthenticatedCommitteeAppealsRoute,
  AuthenticatedSupervisorInboxRoute: AuthenticatedSupervisorInboxRoute,
  AuthenticatedSupervisorReviewIdRoute: AuthenticatedSupervisorReviewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
